// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "UniPurge/Enums.h"
#include <vector>
#include <stdexcept>
#include <map>

/* Class used to generate the world in which the game takes place */
class UNIPURGE_API WorldGenerator
{
public:
	
	/**
	* Main constructor of the class, used to initialize properly
	* @param H : The height of the grid
	* @param W : The width of the grid
	* @param MR : The maximum range of influence
	*/
	WorldGenerator( int H, int W, int MR);
	/* Empty constructor to simply generate the class*/
	WorldGenerator();
	/* Class destructor*/
	~WorldGenerator();

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = GenerationOptions)
		/* Height of the world generated (2D) */
		int Height;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = GenerationOptions)
		/* Width of the world generated (2D) */
		int Width;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = GenerationOptions)
		/* Maximum influence range */
		int MaxRange;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = GenerationOptions)
		/* Influence generated by buildings */
		int BuildingInfluence;


	/* Returns the most influenced point in the grid in coordinates */
	std::pair<int, int> GetMostInfluenced();

	void FixList();

	/**
	* Function called whenever an element is added to the grid. Used to recalculate the map
	* @param X : The X position in the grid
	* @param Y : The Y position in the grid
	*/
	void AddItem(int X, int Y, Block UsedTile);

	/**
	* Function called to get the influence of a certain point in the grid
	* @param X : The X position in the grid
	* @param Y : The Y position in the grid
	*/
	int GetInfluence(int X, int Y);

	/**
	* Public function used to receive the block in a certain location
	* @param X : The X position in the grid
	* @param Y : The Y position in the grid
	*/
	Block GetBlock(int X, int Y);

protected:
	/* Tile map used to guide generation */
	std::vector<Tile> TileMap;

private:
	int iterator;

	/* Priority List used to check for max influence*/
	//std::priority_queue<Tile*, std::vector<Tile*>, CustomCompare> InfluenceList;
	std::multimap <int, Tile*> InfluenceList;

	/**
	* Function used to recalculate the influence in a certain road
	* @param Pos : The position of the road in the grid
	* @param VisitedList : The list which has all the visited positions in the grid
	*/
	void RecalculateRoad(int Pos, int InfluenceGain, std::vector<int>* VisitedList);

	/**
	* Recursive function called by "RecalculateRoad" and used to recalculate the influence in a certain nothing spot
	* @param Pos : The position of the element in the grid
	* @param InfluenceGain : The gain of influence to the element
	* @param RemainingRange : The remaining range for the recursion
	*/
	void RecalculateNext(int Pos, int InfluenceGain, int RemainingRange, std::vector<int>* VisitedList);

	/**
	* Recursive function called by "AddItem" and used to find all roads inside its influence area
	* @param Pos : The position of the road in the grid
	* @param RemainingInfluence : The remaining influence of the building
	* @param RemainingRange : The remaining range for the recursion
	*/
	void CheckRoads(int Pos, int RemainingInfluence, int RemainingRange, std::vector<int>* VisitedList);

	/**
	* Function used to attain the Array position of a 2D position
	* @param Columna : The X Position ->
	* @param Fila : The Y Position ^
	*/
	Tile* get_1d(int Columna, int Fila);
	/**
	* Function used to attain the 2D position from the Array
	* @param Point : The position in the array
	*/
	std::pair<int,int> get_2d(int Pos);

	/**
	* Function used to replace the key of a certain tile in the multimap
	* @param list : The list in which to change the keys
	* @param oldKey : Original key of the pair
	* @param newKey : New key of the pair
	* @param tile : Tile which we are changing from
	*/
	void replace_key(std::multimap <int, Tile*> list, int oldKey, int newKey, Tile* tile);
};




